#TABLE CREATION

CREATE TABLE MEMBERSHIP (
    ABONEMENT_TYPE VARCHAR2(50) PRIMARY KEY,
    VISIT_PER_WEEK NUMBER,
    DAYS_PER_WEEK VARCHAR2(50),
    ATTEND_GROUP_LESSON VARCHAR2(10),
    FAV_GROUP_LESSON VARCHAR2(100)
);

CREATE TABLE TRAINER (
    TRAINER_NAME VARCHAR2(100) PRIMARY KEY
);

CREATE TABLE BRANCH (
    BRANCH_NAME VARCHAR2(100) PRIMARY KEY
);

CREATE TABLE MEMBER (
    ID NUMBER PRIMARY KEY,
    GENDER VARCHAR2(10),
    BIRTHDAY DATE,
    AGE NUMBER,
    ABONEMENT_TYPE VARCHAR2(50),
    TRAINER_NAME VARCHAR2(100),
    BRANCH_NAME VARCHAR2(100),
    FAV_GROUP_LESSON VARCHAR2(100),
    PERSONAL_TRAINING VARCHAR2(10),
    DRINK_ABO VARCHAR2(10),
    FAVORITE_DRINK VARCHAR2(100),
    SAUNA_USAGE VARCHAR2(10),

    CONSTRAINT FK_MEMBER_MEMBERSHIP
        FOREIGN KEY (ABONEMENT_TYPE)
        REFERENCES MEMBERSHIP(ABONEMENT_TYPE),

    CONSTRAINT FK_MEMBER_TRAINER
        FOREIGN KEY (TRAINER_NAME)
        REFERENCES TRAINER(TRAINER_NAME),

    CONSTRAINT FK_MEMBER_BRANCH
        FOREIGN KEY (BRANCH_NAME)
        REFERENCES BRANCH(BRANCH_NAME)
);

CREATE TABLE VISIT_LOG (
    ID NUMBER PRIMARY KEY,
    AVG_TIME_CHECK_IN VARCHAR2(10),
    AVG_TIME_CHECK_OUT VARCHAR2(10),
    TIME_SPENT NUMBER,
    SAUNA_USAGE VARCHAR2(10),
    DRINK_ABO VARCHAR2(10),
    FAVORITE_DRINK VARCHAR2(100),

    CONSTRAINT FK_VISIT_MEMBER
        FOREIGN KEY (ID)
        REFERENCES MEMBER(ID)
);
