#KPI 1: Branches with highest group lesson participation

CREATE TABLE BRANCH_GROUP_ATTENDANCE AS
SELECT 
    BRANCH_NAME,
    COUNT(*) AS TOTAL_MEMBERS,
    COUNT(CASE WHEN ATTEND_GROUP_LESSON = 'TRUE' THEN 1 END) AS GROUP_LESSON_ATTENDEES,
    ROUND(
        COUNT(CASE WHEN ATTEND_GROUP_LESSON = 'TRUE' THEN 1 END) * 100.0 / COUNT(*),
        2
    ) AS ATTENDANCE_PERCENTAGE
FROM MEMBER
GROUP BY BRANCH_NAME;



#KPI 2: Top 3 most popular group lessons

CREATE TABLE TOP_3_GROUP_LESSONS AS
SELECT 
    FAV_GROUP_LESSON,
    COUNT(*) AS COUNT
FROM MEMBER
WHERE FAV_GROUP_LESSON IS NOT NULL
GROUP BY FAV_GROUP_LESSON
ORDER BY COUNT DESC
FETCH FIRST 3 ROWS ONLY;



#KPI 3: Drink subscription percentage

CREATE TABLE DRINK_PLAN_SUBSCRIPTION AS
SELECT 
    COUNT(CASE WHEN DRINK_ABO = 'TRUE' THEN 1 END) AS SUBSCRIBED_COUNT,
    COUNT(*) AS TOTAL_MEMBERS,
    ROUND(
        COUNT(CASE WHEN DRINK_ABO = 'TRUE' THEN 1 END) * 100.0 / COUNT(*),
        2
    ) AS SUBSCRIPTION_PERCENTAGE
FROM MEMBER;
